Document: ruby2.0
Title: Debian ruby2.0 Manual
Author: <insert document author here>
Abstract: This manual describes what ruby2.0 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ruby2.0/ruby2.0.sgml.gz

Format: postscript
Files: /usr/share/doc/ruby2.0/ruby2.0.ps.gz

Format: text
Files: /usr/share/doc/ruby2.0/ruby2.0.text.gz

Format: HTML
Index: /usr/share/doc/ruby2.0/html/index.html
Files: /usr/share/doc/ruby2.0/html/*.html
